### ISSUE TITLE
Why does the connection to the service fail, is it caused by an incorrect step?

### ISSUE THREAD

**Issue by bai198611** [greengeckowizard/poe-server#2]
Please help me.

**Comment by greengeckowizard** [comment]
Hi can you give more detail on what error your having.

**Comment by greengeckowizard** [comment]
Are you receiving an error like this?
```
tls_client.exceptions.TLSClientExeption: failed to build client out of request input: parse "socks5://user:pass@server:port": invalid port ":port" after host```

**Comment by greengeckowizard** [comment]
> Please help me.

Hi is the issue still happening?

**Comment by greengeckowizard** [comment]
Hi this isn't been showing error on my end I must have fixed it please pull latest changes thank you I'll close this as no further responses. Please recreate if this issue still occurs
