### ISSUE TITLE
Where I enter the proxy

### ISSUE THREAD

**Issue by mmwong1984** [greengeckowizard/poe-server#3]
Birdup, you are not online in discord 🤬🤬. Could you plz add an environment variable for setting up proxy? It will be great.

**Comment by greengeckowizard** [comment]
Yes sure

**Comment by greengeckowizard** [comment]
will make documentation for this

**Comment by greengeckowizard** [comment]
Hi just to clear this issue up you can define the proxy server here in either serverof.py or server.py

```
@app.on_event("startup")
async def startup_event():
    global poe_provider
    poe_provider = PoeProvider(
        POE_TOKENS=[
            "tokengoeshere",
            "tokengoeshere",
            "tokengoeshere",
        ],
        AI_MODEL="chinchilla",
        proxy="socks5://user:pass@server:port",
    )
    ```
    Enter your proxy details where it says  proxy="socks5://user:pass@server:port"
    
    there's documentation in the poe-api if you want to use other protocols for proxy 
    https://github.com/ading2210/poe-api#using-the-client

**Comment by greengeckowizard** [comment]
Update you enter it the same but you now you define it in a .env file see example.env for setting up

**Comment by greengeckowizard** [comment]
you now enter in a coma separated list like you would do as if you were adding poe tokens like 

```
POE_TOKENS="tokengoeshere,tokengoeshere,tokengoeshere"
PROXIES="socks5://user:pass@server:port,socks5://user:pass@server:port"
```

**Comment by greengeckowizard** [comment]
Now enter tokens and proxies in a txt files go rename the example txts to proxies and tokens and you can dump your tokens or proxies inside remember if your proxy doesn't work in the poe api wrapper it won't work in this project. Thank you!!
