### ISSUE TITLE
[Discussion] The stability of this project

### ISSUE THREAD

**Issue by realnoob007** [greengeckowizard/poe-server#5]
Sorry, I don't quite know how the stability of this api is ensured. It's usually to have some problems like “ERROR: websocket: RSV1 set, FIN not set on control” or “Daily usage limit: Beaver .....”. Can this project auto-detect these common errors and change another token and request again? The stability of a poe-wrapper is most crucial from my perspective.

**Comment by greengeckowizard** [comment]
Hi yes I am working on implementing these features where it detects and fixes these common errors. Yes the stability of the poe-wrapper is crucial to this project as its the only way we're able to make the api server function. Soon I'll have some documentation on fixing these weird errors.

**Comment by greengeckowizard** [comment]
Let's continue this on the actual github discussions on this repo please. Also that error should have been patched by now on the poe api wrapper if I'm not mistaken.

**Comment by greengeckowizard** [comment]
https://github.com/greengeckowizard/poe-server/discussions
