### ISSUE TITLE
 [POE_TOKENS: What to Fill in for the Error "p-b='xxxxx'"]

### ISSUE THREAD

**Issue by Summercuisine** [greengeckowizard/poe-server#9]
POE_TOKENS=os.getenv("POE_TOKENS").split(","),
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by greengeckowizard** [comment]
Hi can you make a new clone of the repository you now define the poe tokens and proxies through a txt file see example files on how you can enter it.
